### ISSUE TITLE
xcomponent sample fails to run because FSharp.Core not loaded

### ISSUE THREAD

**Issue by joaomdsc** [xcomponent/xcomponent#6]
The console application in the XComponent samples **xc.helloworld** and **xc.orderprocessing** - and maybe others - fail to run. When I execute the command build\startConsoleApp.cmd (following the README.md), the cmd tool opens and closes immediately. When I cd into **build\consoleApp** and run **OrderProcessingClient.exe**, I get the error message **System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core**. See below for the entire message.

This issue can be worked around by editing OrderProcessing\OrderProcessingClient\OrderProcessingClient\**app-config**, replacing the old version **4.3.1.0** in bindingRedirect with **4.4.0.0**.

-- Joao

d:\w\xc-4.6.5-samples\Examples\xc.orderprocessing\build\consoleApp>OrderProcessingClient.exe 
Init failed : System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at XComponent.Common.Config.DeploymentConfig.LoadConfigFileByName(String name)
   at XComponent.Communication.ClientApi.XcApiHelper..ctor(String pathToXcApiFile) in C:\JenkinsWorkspace\XComponent 4.6.X Patch\XCCommunication\main\ClientApi\XcApiHelper.cs:line 88
   at XCClientAPICommon.ApiExtensions.ApiWrapper`1.Init(String configFile, ClientApiOptions options) in C:\JenkinsWorkspace\XComponent 4.6.X Patch\XCCommunication\main\ClientApi\ApiWrapper.cs:line 29

**Comment by anouarhassine** [comment]
When locating assemblies, the .Net Runtime starts by looking in the **Global Assembly Cache**. It seems that you have a more recent version (4.4.0.0) of _FSharp.Core_ installed and present in the GAC. So modifying the app.config file is indeed the solution here.
